# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKLocationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DKLocationDemo
  
  pod 'BMKLocationKit'
  pod 'Bugly'
  
  target 'DKLocationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DKLocationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
